### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by kinginthenorthcodez**
## Set up a "Hello world" project with two apps 👍🏽 

- Implement a connection between a Ruby on Rails back-end and React front-end.
- Understand pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

### CODE REVIEW

**Review by Whoistolu — COMMENTED** [review]
Hi @kinginthenorthcodez 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted the Set up a "Hello world" project as two apps activity instead of the "Hello world" project as one app with Webpack. kindly submit the right link when requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kinginthenorthcodez** [comment]
Hi, @Whoistolu  wrong submission, resubmitting now.

**Review by Whoistolu — APPROVED** [review]
### Hi @kinginthenorthcodez 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kinginthenorthcodez** [comment]
Merged #1  into dev

**Pull request merged**
